name: mymeal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  http: ^0.13.6
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity: ^3.0.6
  mockito: ^5.4.0
  bloc_test: ^9.1.3
  mocktail: ^0.3.0
  dio: ^5.1.2
  integration_test: ^0.8.1
  google_fonts: ^4.0.4
  dart_date: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
